#!/usr/bin/env ruby
word = %w[dt aeiou bp rl aeiou xyz].map {|x| x[rand(x.size)] }.join('')
punctuation = Array.new(rand(4)+1).map { rand(2).zero? ? '!' : '?' }.join('')
env = ARGV[0] ? " #{ARGV[0]}" : ''
puts word + env + punctuation
