#!/usr/bin/env ruby
word = %w[dt aeiou bp rl aeiou xyz].map { _1.split('').sample }.join('')
punctuation = Array.new(rand(4)+1).map { rand(2).zero? ? '!' : '?' }.join('')
env = ARGV[0] ? ' ' + ARGV[0] : ''
puts word + env + punctuation
